### ISSUE TITLE
64 arithmetic might not work as intended 

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-hal-nxp-jn517x#2]
https://github.com/ARMmbed/mbed-hal-nxp-jn517x/blob/master/source/lp_ticker.c#L295

On the above line a 64 bit arithmetic is intended. cpp specifies the output is only as wide as widest input. Because all the input of that arithmetic are all 32 bit, it will only produce a 32 bit outcome which is not intended behaviour.

**Comment by LiyouZhou** [comment]
This seem to be fixed in ARMmbed/mbed-hal-nxp-jn517x@61549f2, close if you see fit.

**Comment by mlnx** [comment]
@bangaragirinxp is this issue fixed?

**Comment by bangaragirinxp** [comment]
It is fixed. We will close this
